version: "3.2"
services:
  web:
    image: evoting-client:1.0.5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - "API_URL=http://46.137.201.121:3001"
